### PR TITLE
fix: update form submit, make use of env variables

### LINKED ISSUE #10: Fix: Enhance the form submission
some functionality options:
1. the user is able to submit the form and send the input value as the stock ticker payload
2. the user is not able to submit the form, and must choose from the buttons in the drop down (so would need to re-add the preventDefault
3. the user is able to submit the form only if the input value matches one of the options
4. the user is able to submit the form and the first option is sent as the stock ticker payload

_Originally posted by @gracescharf in https://github.com/iprado78/fullstack-iex-stock-ticker/pull/8#discussion_r605739431_

### PR DESCRIPTION
**Pull request by gracescharf**
# Description
Update form submit so that submitting the form brings focus to the first available option. I would probably use a class rather than just the button tag, but just being a little lazy?

Also, I'm pretty sure I can't use a ref here, since the buttons are output in a conditional loop -- is that correct? 

# Related Issues
Closes #10

### CODE REVIEW

**Review by dwalker11 — APPROVED** [review]

File: pages/api/company-overview/[symbol].ts [hunk 1]
```diff
@@ -2,7 +2,7 @@ import axios from "axios"
 import { ICompanyOverview } from "../../../models/CompanyOverview"
 
 const BASE_URL = "https://cloud.iexapis.com"
-const TOKEN = "pk_63509e5b43384ab08845be28759fb5ea"
+const TOKEN = process.env["IEX_API_TOKEN"];
```
Comment (iprado78) [inline pages/api/company-overview/[symbol].ts:5]: We should wrap this ceremony in an abstraction shared by our API routes

**Review by iprado78 — APPROVED** [review]
